### ISSUE TITLE
$** + UDPspeeder + udp2raw 下的 iperf3测速

### ISSUE THREAD

**Issue by gemhowie** [wangyu-/UDPping#1]
@wangyu-  你好，有个问题想向你请教

问题: 如何在下面这种方案中用 iperf3 测加速后的 udp

$** + UDPspeeder + udp2raw

tcp 用 tinymapper 转发，走BBR，udp 走 UDPspeeder + udp2raw

server端，$**server端口7788

```sh
nohup ./speederv2_amd64 -s -l0.0.0.0:4010 -r127.0.0.1:7788 -k "passwd" -f20:10 --mode 0 -i 10 --report 20 > ./speeder.log 2>&1 &
nohup ./udp2raw_amd64 -s -l0.0.0.0:4020 -r127.0.0.1:4010  -a -k "passwd" --raw-mode faketcp --cipher-mode xor > ./udp2raw_udp.log 2>&1 &
```

client端，$**redir 本地监听端口1080 -> server 127.0.0.1:6010

```sh
nohup ./tinymapper_amd64 -l0.0.0.0:6010 -r$server:7788 -t > ./tinymapper.log 2>&1 &
nohup ./speederv2_amd64 -c -l0.0.0.0:6010 -r127.0.0.1:4021 -k "passwd" -f20:10 --mode 0 -i 10  --report 20 > ./speeder.log 2>&1 &
nohup ./udp2raw_amd64 -c -l0.0.0.0:4021 -r$server:4020  -a -k "passwd" --raw-mode faketcp --cipher-mode xor > ./udp2raw_udp.log 2>&1 &
```

UDPping测加速后的udp延迟，没有问题，引入少量延迟，丢包率降到0

server端

```sh
 socat -v UDP-LISTEN:7788,fork PIPE
```

client端

```sh
~/udpping.py 127.0.0.1 1080
```

目前想要测试加速后的udp速度，用iperf3，版本3.5

3.5版本iperf3不支持在server端设定 -u 选项，改成自适应client端参数，这样导致无法监听 7788/udp 端口，我试过用tinymapper将 7788 映射到 5003 ，然后iperf3 监听 5003

server端

```sh
nohup ./tinymapper_amd64 -l0.0.0.0:5003 -r127.0.0.1:7788 -u > ./tinymapper.log 2>&1 &
iperf3 -s -p 5003
```

client端

```sh
iperf3 -c 127.0.0.1 -p 1080 -u -i 1 -b 5M -t 60
```

提示 iperf3: error - control socket has closed unexpectedly

虽然跟UDPping没关系，但是希望你能够帮忙解答，这两种方式为什么UDPping可以，iperf3不行。

或者有没有其他更好的测试加速后udp性能的方法。

**Comment by wangyu-** [comment]
>3.5版本iperf3不支持在server端设定 -u 选项，改成自适应client端参数，这样导致无法监听 7788/udp 端口，我试过用tinymapper将 7788 映射到 5003 ，然后iperf3 监听 5003

开始测试后就监听了。

我有点看不懂你的iper3和tinyportmapper连法。你直接用下面的连法：

你让iperf3监听在远程的1111  ，然后你用tinyPortMapper把远程的tcp1111端口映射到本地的2222，用udpspeeder+udp2raw把远程的udp1111端口映射到本地的2222。 然后在本地用iperf3 client连本地的2222测试。我以前试过，是可以的。

测试udp时候注意一下 `-l` 选项(控制mtu)和`--pacer-timer`选项。默认参数不靠谱。参考：
https://github.com/wangyu-/tinyPortMapper/wiki/Performance-Test

**Comment by gemhowie** [comment]
> 你让iperf3监听在远程的1111 ，然后你用tinyPortMapper把远程的tcp1111端口映射到本地的2222，用udpspeeder+udp2raw把远程的udp1111端口映射到本地的2222。 然后在本地用iperf3 client连本地的2222测试。我以前试过，是可以的。

我试过了，这样确实可以，不过我想要加上$**测，这样的话iperf3的server端需要监听tcp/udp端口，而$*server也要监听tcp/udp端口，不管怎么转发，都会有一个程序会没办法启动

```
unable to start listener for connections: Address already in use
```

有什么办法能加上$**来测吗

**Comment by gemhowie** [comment]
我想套$$来测是因为我一直怀疑我转发 udp 的方式有问题，我的 $*-redir 是跑在本机上的

严格来用，$*-redir应该运行在网关上，然后用TPROXY来转发，这样不会做dnat

可是我的 $*-redir 跑在本机上，因为TPROXY只工作在mangle/PREROUTING，没办法对本地udp进行转发，用 iptables 的redirect 转发udp数据包时会做dnat，导致原始目的地址丢失。

我做了测试

用iptables限制了本机访问server的端口，只允许$*-server tcp端口，udp2raw server udp端口，目的是强制iperf3走 $*通道

然后用iperf3测

server
```
iperf3 -s -p 3333
```
client
```
iperf3 -c <server ip> -p 3333 -u -i 1 -b 5M
```

在server端发现有来自 server ip : port 连接的请求，然后并没有继续输出结果，卡住了。
```
Accepted connection from (server ip), port 45368
```

redirect 的 udp包，目的ip应该变成了127.0.0.1，不知道为什么数据包到了 server 端与 iperf3 server 端口连接时是显示来自 server ip : port 的连接，中间有做 snat 吗？

我是不是应该放弃在本机上用 iptables redirect 来转发udp

路由器暂时不考虑，在本机上跑个虚拟机做网关，$$-redir放上面看起来可行，不知道还有没有其他方案

**Comment by wangyu-** [comment]
你可以看下$$-tunnel这个命令，能把$$串上去，不知是否满足需求？  

如果必须测$$-redir这个命令，除了`把$$-redir跑在网关上，在网关后面用Iperf3测`以外，我也想不到什么好办法了。

**Comment by gemhowie** [comment]
$*-redir 在本地跑转发本地udp确实是有问题的，目前已经改用 tun2socks 方案，UDPping 和 iperf3 测试均无问题
