### ISSUE TITLE
Patch to flush output

### ISSUE THREAD

**Issue by TimAuckland** [wangyu-/UDPping#4]
udpping writes its response output to stdout with default stdio buffering, which is ok for interactive terminal use, but doesn't work well if udpping is being called from a script, or otherwise has it's output redirected.

Please find attached a patch which adds explicit output flushing.

Tim

[udpping_flush_patch.txt](https://github.com/wangyu-/UDPping/files/3140402/udpping_flush_patch.txt)

**Comment by wangyu-** [comment]
Hi, thank you, merged.

I havnt tested your [another patch](https://github.com/wangyu-/UDPping/issues/3) yet. The current problem is I dont have an envirment right now, will test later. 

BTW, its suggested to send a pull request next time😂
